[#schema-reference-tilers]
== JSON Schema for Tilers Options

[source,json]
----
include::../tilers/config/tilers/schema/tilers.schema.json[]
----

<<<


[#schema-reference-input]
== JSON Schema for Input Options

[source,json]
----
include::../tilers/config/tilers/schema/input.schema.json[]
----

<<<


[#schema-reference-output]
== JSON Schema for Output Options

[source,json]
----
include::../tilers/config/tilers/schema/output.schema.json[]
----

<<<


[#schema-reference-tileset]
== JSON Schema for Tileset Options

[source,json]
----
include::../tilers/config/tilers/schema/tileset.schema.json[]
----

<<<


[#schema-reference-gltf]
== JSON Schema for Gltf Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.schema.json[]
----

<<<


[#schema-reference-obj]
== JSON Schema for OBJ Options

[source,json]
----
include::../tilers/config/tilers/schema/obj.schema.json[]
----

<<<


[#schema-reference-csv]
== JSON Schema for CSV Options

[source,json]
----
include::../tilers/config/tilers/schema/csv.schema.json[]
----

<<<


[#schema-reference-pipeline]
== JSON Schema for Pipeline Options

[source,json]
----
include::../tilers/config/tilers/schema/pipeline.schema.json[]
----

<<<


[#schema-reference-advanced]
== JSON Schema for Advanced Options

[source,json]
----
include::../tilers/config/tilers/schema/advanced.schema.json[]
----

<<<


[#schema-reference-georeference]
== JSON Schema for Georeference Options

[source,json]
----
include::../tilers/config/tilers/schema/georeference.schema.json[]
----

<<<


[#schema-reference-georeference-position]
== JSON Schema for Georeference Position Options

[source,json]
----
include::../tilers/config/tilers/schema/georeference.position.schema.json[]
----

<<<


[#schema-reference-georeference-orientation]
== JSON Schema for Georeference Orientation Options

[source,json]
----
include::../tilers/config/tilers/schema/georeference.orientation.schema.json[]
----

<<<


[#schema-reference-georeference-scale]
== JSON Schema for Georeference Scale Options

[source,json]
----
include::../tilers/config/tilers/schema/georeference.scale.schema.json[]
----

<<<


[#schema-reference-gltf-attributes]
== JSON Schema for Gltf Attribute Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.attributes.schema.json[]
----

<<<


[#schema-reference-gltf-indices]
== JSON Schema for Gltf Indices Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.indices.schema.json[]
----

<<<


[#schema-reference-gltf-textures]
== JSON Schema for Gltf Texture Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.textures.schema.json[]
----

<<<


[#schema-reference-gltf-draco]
== JSON Schema for Draco Model Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.draco.schema.json[]
----

<<<


[#schema-reference-gltf-attributes-position]
== JSON Schema for Position Attribute Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.attributes.position.schema.json[]
----

<<<


[#schema-reference-gltf-attributes-normal]
== JSON Schema for Normal Attribute Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.attributes.normal.schema.json[]
----

<<<


[#schema-reference-gltf-attributes-tangent]
== JSON Schema for Tangent Attribute Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.attributes.tangent.schema.json[]
----

<<<


[#schema-reference-gltf-attributes-texcoord]
== JSON Schema for Texcoord Attribute Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.attributes.texcoord.schema.json[]
----

<<<


[#schema-reference-gltf-attributes-color]
== JSON Schema for Color Attribute Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.attributes.color.schema.json[]
----

<<<


[#schema-reference-gltf-attributes-joints]
== JSON Schema for Joints Attribute Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.attributes.joints.schema.json[]
----

<<<


[#schema-reference-gltf-attributes-weights]
== JSON Schema for Weights Attribute Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.attributes.weights.schema.json[]
----

<<<


[#schema-reference-gltf-attributes-featureid]
== JSON Schema for Feature ID Attribute Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.attributes.featureId.schema.json[]
----

<<<


[#schema-reference-gltf-attributes-generic]
== JSON Schema for Generic Attribute Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.attributes.generic.schema.json[]
----

<<<


[#schema-reference-attribute]
== JSON Schema for Attribute Options

[source,json]
----
include::../tilers/config/tilers/schema/attribute.schema.json[]
----

<<<


[#schema-reference-attribute-draco]
== JSON Schema for Draco Attribute Options

[source,json]
----
include::../tilers/config/tilers/schema/attribute.draco.schema.json[]
----

<<<


[#schema-reference-meshopt]
== JSON Schema for Meshopt Options

[source,json]
----
include::../tilers/config/tilers/schema/meshopt.schema.json[]
----

<<<


[#schema-reference-quantization]
== JSON Schema for Quantization Options

[source,json]
----
include::../tilers/config/tilers/schema/quantization.schema.json[]
----

<<<


[#schema-reference-gltf-textures-basecolor]
== JSON Schema for Base Color Texture Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.textures.baseColor.schema.json[]
----

<<<


[#schema-reference-gltf-textures-metallicroughness]
== JSON Schema for Metallic Roughness Texture Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.textures.metallicRoughness.schema.json[]
----

<<<


[#schema-reference-gltf-textures-emissive]
== JSON Schema for Emissive Texture Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.textures.emissive.schema.json[]
----

<<<


[#schema-reference-gltf-textures-normal]
== JSON Schema for Normal Texture Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.textures.normal.schema.json[]
----

<<<


[#schema-reference-gltf-textures-occlusion]
== JSON Schema for Occlusion Texture Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.textures.occlusion.schema.json[]
----

<<<


[#schema-reference-gltf-textures-featureid]
== JSON Schema for Feature Id Texture Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.textures.featureId.schema.json[]
----

<<<


[#schema-reference-gltf-textures-property]
== JSON Schema for Property Texture Options

[source,json]
----
include::../tilers/config/tilers/schema/gltf.textures.property.schema.json[]
----

<<<


[#schema-reference-texture]
== JSON Schema for Texture Options

[source,json]
----
include::../tilers/config/tilers/schema/texture.schema.json[]
----

<<<


[#schema-reference-texture-sampler]
== JSON Schema for Texture Sampler Options

[source,json]
----
include::../tilers/config/tilers/schema/texture.sampler.schema.json[]
----

<<<


[#schema-reference-image]
== JSON Schema for Image Options

[source,json]
----
include::../tilers/config/tilers/schema/image.schema.json[]
----

<<<


[#schema-reference-png]
== JSON Schema for Png Options

[source,json]
----
include::../tilers/config/tilers/schema/png.schema.json[]
----

<<<


[#schema-reference-jpeg]
== JSON Schema for Jpeg Options

[source,json]
----
include::../tilers/config/tilers/schema/jpeg.schema.json[]
----

<<<


[#schema-reference-ktx2etc1s]
== JSON Schema for Ktx2 Etc1s Options

[source,json]
----
include::../tilers/config/tilers/schema/ktx2Etc1s.schema.json[]
----

<<<


[#schema-reference-ktx2uastc]
== JSON Schema for Ktx2 Uastc Options

[source,json]
----
include::../tilers/config/tilers/schema/ktx2Uastc.schema.json[]
----

<<<


[#schema-reference-csvproperty]
== JSON Schema for CSV Property

[source,json]
----
include::../tilers/config/tilers/schema/csvProperty.schema.json[]
----

<<<


[#schema-reference-pipeline-processgltf]
== JSON Schema for PROCESS_GLTF Pipeline Options

[source,json]
----
include::../tilers/config/tilers/schema/pipeline.processGltf.schema.json[]
----

<<<


[#schema-reference-pipeline-processtileset]
== JSON Schema for PROCESS_TILESET Pipeline Options

[source,json]
----
include::../tilers/config/tilers/schema/pipeline.processTileset.schema.json[]
----

<<<


[#schema-reference-pipeline-photogrammetrytiler]
== JSON Schema for PHOTOGRAMMETRY_TILER Pipeline Options

[source,json]
----
include::../tilers/config/tilers/schema/pipeline.photogrammetryTiler.schema.json[]
----

<<<


[#schema-reference-pipeline-voxeltiler]
== JSON Schema for VOXEL_TILER Pipeline Options

[source,json]
----
include::../tilers/config/tilers/schema/pipeline.voxelTiler.schema.json[]
----

<<<


[#schema-reference-pipeline-convertmodel]
== JSON Schema for CONVERT_MODEL Pipeline Options

[source,json]
----
include::../tilers/config/tilers/schema/pipeline.convertModel.schema.json[]
----

<<<


[#schema-reference-pipeline-pointcloudtogltf]
== JSON Schema for POINT_CLOUD_TO_GLTF Pipeline Options

[source,json]
----
include::../tilers/config/tilers/schema/pipeline.pointCloudToGltf.schema.json[]
----

<<<


[#schema-reference-pipeline-b3dmtogltf]
== JSON Schema for B3DM_TO_GLTF Pipeline Options

[source,json]
----
include::../tilers/config/tilers/schema/pipeline.b3dmToGltf.schema.json[]
----

<<<


[#schema-reference-pipeline-printstats]
== JSON Schema for PRINT_STATS Pipeline Options

[source,json]
----
include::../tilers/config/tilers/schema/pipeline.printStats.schema.json[]
----

<<<


[#schema-reference-pipeline-voxeltiler-grid]
== JSON Schema for VOXEL_TILER Pipeline grid Options

[source,json]
----
include::../tilers/config/tilers/schema/pipeline.voxelTiler.grid.schema.json[]
----

<<<


